SRCS =		Brain.cpp \
 			Human.cpp \
			main.cpp

INCLUDES =	Human.hpp \
			Brain.hpp

NAME =		Human

FLAGS =		-Wall -Wextra -Werror

all: 		$(NAME)

$(NAME):	$(INCLUDES) $(SRCS)
			clang++ $(SRCS) $(FLAGS) -o $@

clean:
			@rm -rf *.o

fclean:		clean
			@rm -rf $(NAME)

re:			fclean all

.PHONY: 	all clean fclean re